### ISSUE TITLE
Add `confirmations` to transactions

### ISSUE THREAD

**Issue by cimm** [biteasy/blockchain-api#10]
Would it be possible to add a `confirmations` field to the API? [Blockchain](https://blockchain.info/unspent?active=3F1hoHt1NXSmPqdPV5ZtBtLCucA9SaNen9), [Blockr](http://btc.blockr.io/api/v1/address/unspent/198aMn6ZYAczwrE5NvNTUMyJ5qkfy4g3Hi,1L8meqhMTRpxasdGt8DHSJfscxgHHzvPgk) and [Insight](http://test.insight.is/api/txs/?address=2MxjnBW7CZ5tEgSQfdgzgPKYetZCNwPLYez) have that info but Biteasy does not so I am stuck querying multiple APIs to get all the data I need. Would be nice to simply rely on Biteasy.

**Comment by biteasy** [comment]
Transactions do have a `confirmations` field already actually. 

Did you mean that you need this in the [/unspent-outputs](https://support.biteasy.com/kb/rest-api/endpoints/unspent-outputs) API?

**Comment by cimm** [comment]
Yes, sorry, should have specified this. I meant the [/unspent-outputs](https://api.biteasy.com/testnet/v1/addresses/2MxjnBW7CZ5tEgSQfdgzgPKYetZCNwPLYez/unspent-outputs) endpoint.

**Comment by schildbach** [comment]
I'm also running into this issue. At least we should get the information if an unspent output is confirmed by the blockchain at all.

**Comment by biteasy** [comment]
We still haven't decided about this. I will get back to you guys soon.

**Comment by biteasy** [comment]
We decided to implement this and it will be done very soon. I will give you an update guys for release date.

**Comment by schildbach** [comment]
That's good to hear!

It seems as if currently the API makes visible UXTOs created by pending transactions, but when I spend those UXTOs it needs a blockchain confirmation until that state is reflected by the API. I take it this weirdness will go away when you implement this feature?

**Comment by biteasy** [comment]
OK, it's now more clear to me why you need that `confirmations` field. 

We will provide a couple of solutions to this in a few days so you can filter the unspent outputs that you want.

**Comment by alolis** [comment]
This has been implemented in `v2` but it's still in beta.
https://support.biteasy.com/kb/v2-0

The `state` field is the one you need :)
