### ISSUE TITLE
Differences between Blockchain and Biteasy

### ISSUE THREAD

**Issue by cimm** [biteasy/blockchain-api#11]
I am comparing the Blockchain.info and Biteasy API's. Here is an example of the unspent outputs endpoint for the same multisig address for both services. I understand there are small differences between both API's but they seem to differ heavily.
- [x] The `tx_hash` _(db29...)_ and `transaction_hash` _(9e07...)_ are not the same?
- [x] The `tx_index` _(5480...)_ and `transaction_index` _(0)_ are not even close, I guess the `transaction_index` from Biteasy matches with the `tx_output_n`?
- [x] The `script` _(a914...)_ and `script_pub_key` _(HASH...)_  are in a different format, I guess you can encode one in the other?

Do both API's simply use different ways to present the same data or is the data different between the two?
## BLOCKCHAIN

https://blockchain.info/unspent?active=3CmmhMciChAx4FtGxHtYppoPBLpRLcBy1H

``` json
{
"tx_hash": "db29f6a52fa09bf852cefd514fdd71027894f2b19f6fc752cb5e001dc323079e",
"tx_index": 54805310,
"tx_output_n": 0,
"script": "a914798f9646eb0c7efdd33eaf019a35fc6e37bffb4287",
"value": 100000,
"value_hex": "0186a0",
"confirmations": 1369
}
```
## BITEASY

https://api.biteasy.com/blockchain/v1/addresses/3CmmhMciChAx4FtGxHtYppoPBLpRLcBy1H/unspent-outputs

``` json
{
"transaction_hash": "9e0723c31d005ecb52c76f9fb1f294780271dd4f51fdce52f89ba02fa5f629db",
"script_pub_key": "HASH160 [798f9646eb0c7efdd33eaf019a35fc6e37bffb42] EQUAL",
"to_address": "3CmmhMciChAx4FtGxHtYppoPBLpRLcBy1H",
"value": 100000,
"transaction_index": 0,
"is_spent": 0,
"script_sent_type": "PAY_TO_HASH"
}
```

**Comment by cimm** [comment]
To answer my first question, it's a difference between little and big endians. The Blockchain transaction hash is the _reverse_ of the Biteasy one. :facepunch: Thanks [Buziss](https://bitcointalk.org/index.php?topic=587741.msg6440735#msg6440735).

@biteasy Why didn't you stick to the way `bitcoind` reports transaction ids?

**Comment by biteasy** [comment]
1. We use big endian format for displaying transaction hashes. `bitcoind` displays them in the same way and I believe Blockchain.info does the same thing. I do not why they show the specific transaction reversed. Maybe a bug on their side?
2. The `tx_index` which blockchain.info uses I assume is their internal MySQL ids. Our transaction_index is the position of the output within the outputs array.
3. Their `script` is the hex encoded string value and ours is converted to a readable string which contains the OP codes as well but we will probably provide the hex encoded string value in the future if a lot of API users request it. The value we provide is basically intended for displaying (like on our Testnet pages).

Blockchain.info does things their way and we are doing things our way :)

Let us know if you have more questions and my apologies for the small delay but it has been crazy here, we will be adding more coins to the site and we are in the middle of changing our infrastructure a bit.

**Comment by cimm** [comment]
Indeed, it seems Blockchain.info reverts the transaction_id around, not Biteasy. Sorry for that.

Thank you for helping me out!
