### ISSUE TITLE
Add script bytes to API results

### ISSUE THREAD

**Issue by schildbach** [biteasy/blockchain-api#13]
Whereever the API returns a script, it should also return the unparsed version of the script, so just the bytes (hex encoded).

More concrete, I'd need it for the unspent outputs:
https://api.biteasy.com/testnet/v1/unspent-outputs?address[]=mm4RrYHaQWqSt1SpQATzMR8abTBVdMQ4Qz

**Comment by biteasy** [comment]
I agree. It will be added very soon.

**Comment by biteasy** [comment]
It will be implemented tomorrow first thing. I will let you know as soon as it's done.

**Comment by biteasy** [comment]
`Implemented`

`output->script_pub_key` and `input->script_sig` will now contain the hex encoded values of the script and `output->script_pub_key_string` and `input->script_sig_string` the friendly versions of the script which is useful for display purposes only.

**Comment by schildbach** [comment]
Thanks a lot!

**Comment by schildbach** [comment]
It works flawlessly afaict.

**Comment by biteasy** [comment]
Good to know, let me know if you see anything weird.
