### ISSUE TITLE
Add magic constant MAX to &per_page parameter

### ISSUE THREAD

**Issue by schildbach** [biteasy/blockchain-api#17]
I'm opening a separate ticket for this idea, because it's independant from the other tickets.

The idea is that a client can use a stable URL if he wants to raise the number of results to whatever maximum the API will want to serve. The client will specify &per_page=MAX

Also see: https://github.com/biteasy/blockchain-api/issues/16#issuecomment-45598846

(This is currently the blocking issue for releasing the swipe wallet feature of Bitcoin Wallet to the public.)

**Comment by biteasy** [comment]
It will be implemented ASAP. Sorry for the small delay, I know I promised it.

**Comment by biteasy** [comment]
It will be implemented tomorrow morning

**Comment by biteasy** [comment]
`Implemented`

Let me know if you find any problems
