### ISSUE TITLE
Performance issue with addresses many unspent outputs

### ISSUE THREAD

**Issue by erasmospunk** [biteasy/blockchain-api#18]
Tried a random address with a lot of unspent outputs and the server takes a lot of time to return on higher pages. It gets even worse that on page 9 it crashes completely

https://api.biteasy.com/blockchain/v1/addresses/1CjPR7Z5ZSyWk6WtXvSFgkptmpoi4UM9BC/unspent-outputs?per_page=40&page=9

Thanks!

**Comment by biteasy** [comment]
Hm, this needs a little bit more investigation...

**Comment by biteasy** [comment]
We have identified the problem. Fix under way

**Comment by erasmospunk** [comment]
great!

**Comment by biteasy** [comment]
Is it fast enough for you now? :)

Also, we have increased the maximum per_page limit from 40 to 200 so you can use that as well.

**Comment by erasmospunk** [comment]
It is much better, thanks!
