### ISSUE TITLE
/unspent-outputs returns spent outputs

### ISSUE THREAD

**Issue by schildbach** [biteasy/blockchain-api#20]
I suspect the UXTO API returns bad results since a few days. Consider this call:

https://api.biteasy.com/testnet/v1/unspent-outputs?address[]=mm4RrYHaQWqSt1SpQATzMR8abTBVdMQ4Qz

It returns several unspent outputs. Now see the same address on this URL, its got a balance of 0:

https://www.biteasy.com/testnet/addresses/mm4RrYHaQWqSt1SpQATzMR8abTBVdMQ4Qz

I did not send any coins from or to this address for about 2 weeks. I _think_ when I last checked, the above API call returned an empty list (as expected). It feels as if some server change during the last few days regressed the expected result to something unexpected.

**Comment by biteasy** [comment]
`Fixed`

Sorry about this, silly mistake.
