### ISSUE TITLE
/addresses/{address}/unspent-outputs error

### ISSUE THREAD

**Issue by dcousens** [biteasy/blockchain-api#22]
**Example**: https://api.biteasy.com/blockchain/v1/addresses/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp/unspent-outputs

**Current output**:

> {"status":500,"code":500,"messages":"A serious internal error has occured. Please notify the monkeys!"}

If this API has been deprecated in favour of https://api.biteasy.com/blockchain/v1/unspent-outputs/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp, is it possible you could please update the documentation?

**Comment by biteasy** [comment]
Hello,

The API endpoint is not deprecated. It was just a glitch on the service today which was fixed few minutes ago. 
Thanks for reporting!
