### ISSUE TITLE
Websockets failure 

### ISSUE THREAD

**Issue by sudo-ben** [biteasy/blockchain-api#23]
var mySocket = new WebSocket('wss://ws.biteasy.com/blockchain/v1');
WebSocket connection to 'wss://ws.biteasy.com/blockchain/v1' failed: Error during WebSocket handshake: Unexpected response code: 502

**Comment by biteasy** [comment]
Hello,

It should be ok now. We were having a small issue with the websockets server.

**Comment by sudo-ben** [comment]
I seems to still be having issues getting a response. Not getting responces

```
        mySocket.send(JSON.stringify({
            "event": "transactions:*",
            "filters": {
                "addresses": [...],
                "confidence": "0"
            }
        }));
```

to this

**Comment by biteasy** [comment]
Hello,

The confidence you are using is not correct. You should be using string constants which can be found [here](https://support.biteasy.com/kb/api-constants). There are also a couple of examples with transactions [here](https://support.biteasy.com/kb/websockets-api/events/transactions).

Let me know if you are still having issues.

**Comment by sudo-ben** [comment]
My mistake. Thanks for the reply. Yes that was the issue.

**Comment by biteasy** [comment]
No problem :)
