### ISSUE TITLE
Address Details not showing in Firefox on Android

### ISSUE THREAD

**Issue by flowolf** [biteasy/blockchain-api#24]
when browsing addresses in Firefox on Android the site does not show any details. Just the website's header is loaded.
![screenshot_2014-08-14-08-17-14](https://cloud.githubusercontent.com/assets/900893/3916463/07fd862c-237b-11e4-88ec-579d6a3ee032.png)

Details load fine in Chrome on Android. A little later than the main site, but details show up. Not so in Firefox.

**Comment by alolis** [comment]
Hello,

We tested under 4.4.2 (tablet) and 4.0 (mobile) with latest Firefox and everything seems to work just fine. The only reason I can think of is some kind of Firefox extension you might have installed that is blocking the content to load properly (adblock maybe or some other javascript blocker?)

![10453324_347166315441769_2467918709700781351_n](https://cloud.githubusercontent.com/assets/82233/3996134/b418bfce-2931-11e4-965f-d41abc9fd016.jpg)

![10481665_347166072108460_1368301105517851294_n](https://cloud.githubusercontent.com/assets/82233/3996135/b41e5d94-2931-11e4-8276-767a5840fdf4.jpg)

![10613867_347157612109306_1280538025_n](https://cloud.githubusercontent.com/assets/82233/3996136/b424a1a4-2931-11e4-8014-f859071bf293.jpg)

![10637947_347157632109304_1087121133_n](https://cloud.githubusercontent.com/assets/82233/3996137/b42778a2-2931-11e4-9024-679a73f7977d.jpg)

**Comment by flowolf** [comment]
had AdBlock Plus 2.6.4 active and Proxy Mobile 0.0.10 active, not set up though.

works fine after disabling Proxy Mobile.
works fine with AdBlock Plus active!

thanks for checking!
keep up the good work.
