### ISSUE TITLE
Add two fields missing from transaction fetch API

### ISSUE THREAD

**Issue by richardkiss** [biteasy/blockchain-api#26]
If you look at the output for https://api.biteasy.com/blockchain/v1/transactions/d1ef46055a84fd02ee82580d691064780def18614d98646371c3448ca20019ac you will see that there is no way to determine that this transaction has an input with a nonstandard lock time (it's usually 0, but in this rare case it's not).

This makes is impossible to reconstruct the original transaction.

The transaction value for nSequence is not included in the output either, and probably should be for completeness. (I do not have any examples of transactions in the blockchain where this is a non-standard value at this time.)

The reason I want these values is so I can take the JSON and turn it into a binary that matches the original transaction. This is easy with other services; see https://github.com/richardkiss/pycoin/blob/master/pycoin/services/blockr_io.py for an example.

**Comment by alolis** [comment]
Just wanted to give you a delayed update about this since I've just realized that we've never replied to you.

With the current structure of our services this is not possible BUT we are in the testing phase of version 2.0 of our API which will include what you want.

**Comment by alolis** [comment]
This has been implemented in `v2` of the REST API
https://support.biteasy.com/kb/v2-0

**Comment by richardkiss** [comment]
I don't see the sequence number in the output (and these are going to be useful pretty soon).

**Comment by alolis** [comment]
@richardkiss,  Are you referring to input sequence as described here? https://en.bitcoin.it/wiki/Protocol_documentation
