### ISSUE TITLE
Incorrect Input Address Coming From Multisig Output

### ISSUE THREAD

**Issue by jpe42** [biteasy/blockchain-api#27]
For transaction ba44cc1e1d2aa767ac6b32b4c8f931ccffa6e81858de6f5a297a8ceebe85ea05 Biteasy is showing a different address than blockchain.info, blockr, chain and sochain:

https://api.biteasy.com/blockchain/v1/transactions/ba44cc1e1d2aa767ac6b32b4c8f931ccffa6e81858de6f5a297a8ceebe85ea05

https://blockchain.info/tx/ba44cc1e1d2aa767ac6b32b4c8f931ccffa6e81858de6f5a297a8ceebe85ea05?format=json

https://chain.so/api/v2/tx/BTC/ba44cc1e1d2aa767ac6b32b4c8f931ccffa6e81858de6f5a297a8ceebe85ea05

https://api.chain.com/v1/bitcoin/transactions/ba44cc1e1d2aa767ac6b32b4c8f931ccffa6e81858de6f5a297a8ceebe85ea05?api-key-id=DEMO-4a5e1e4

http://btc.blockr.io/api/v1/tx/info/ba44cc1e1d2aa767ac6b32b4c8f931ccffa6e81858de6f5a297a8ceebe85ea05

I would assume it is an issue with handling inputs that come from a multisig output, but not sure.

**Comment by alolis** [comment]
Yes, you are right. That is not what it should show there. It's a bug on our side which we are fixing.

**Comment by alolis** [comment]
We are in the process of releasing a v2.0 of the website and this will be resolved once and for all
