### ISSUE TITLE
Method to find transactions by address and block fails

### ISSUE THREAD

**Issue by ghgr** [biteasy/blockchain-api#28]
Example: Find transactions of 1NXYoJ5xU91Jp83XfVMHwwTUyZFK64BoAD in the block with hash 000000000000006a963150feb057e34303095ee00a069e72872bf1ada410cf94
(the URL below is exactly as proposed in the sandbox)

https://api.biteasy.com/blockchain/v1/transactions?address=1NXYoJ5xU91Jp83XfVMHwwTUyZFK64BoAD&block_hash=000000000000006a963150feb057e34303095ee00a069e72872bf1ada410cf94

**Comment by alolis** [comment]
`Fixed`
