### ISSUE TITLE
Wrong current balance api / site

### ISSUE THREAD

**Issue by dranes** [biteasy/blockchain-api#3]
I'm testing your api (on testnet network) and i sent to a new address 1.54 btc and the current balance in the api is 3.09 why ? 

https://www.biteasy.com/testnet/addresses/muVy2RafYwQoHXvxwXSu3yg8CM6Wap61eC

**Comment by biteasy** [comment]
We are investigating and we will get back to you asap

**Comment by biteasy** [comment]
Well, it seems that the reason for this went a bit deeper than we thought so it took longer to track. We are preparing to release an updated version which will fix this so I will let you know when it's ready.

**Comment by dranes** [comment]
Perfect i'll be waiting for that, thanks.

**Comment by biteasy** [comment]
Fixed.

Let us know if you see any more crazy stuff :)

**Comment by dranes** [comment]
:+1:  looks great
