### ISSUE TITLE
biteasy api unspent outputs lies.

### ISSUE THREAD

**Issue by ohadcn** [biteasy/blockchain-api#30]
i couldn't find examples for that on mainnet, but in testnet:
https://api.biteasy.com/testnet/v1/unspent-outputs/miBaPwzENDj4K4dytitWKayvykbG6HpV78
https://www.biteasy.com/testnet/addresses/miBaPwzENDj4K4dytitWKayvykbG6HpV78
the first report ~20 unspents, all of them have nothing to do with that address.

**Comment by alolis** [comment]
Hello,

The API call you are using is wrong. Here is the documentation for it:
https://support.biteasy.com/kb/rest-api/endpoints/address-unspent-outputs

So, the correct API call is:
https://api.biteasy.com/testnet/v1/addresses/miBaPwzENDj4K4dytitWKayvykbG6HpV78/unspent-outputs/

**Comment by ohadcn** [comment]
so you just return random data for wrong calls?

**Comment by alolis** [comment]
Well, it isn't random data exactly. You were using the /unspent-outputs endpoint which returns all the unspent-outputs. The address parameter you were passing was simply ignored. Perhaps it should be changed and throw an error instead of succeeding but documentation is your friend in any case :)
