### ISSUE TITLE
Unable to connect with websocket

### ISSUE THREAD

**Issue by amitabh123** [biteasy/blockchain-api#32]
I tried the echo websocket test from both https and http
https://www.websocket.org/echo.html
http://www.websocket.org/echo.html

I tried following combinations of urls
wss://ws.biteasy.com/blockchain/v1
wss://ws.biteasy.com/blockchain/v1/
ws://ws.biteasy.com/blockchain/v1/
ws://ws.biteasy.com/blockchain/v1

I am unable to connect.

**Comment by alolis** [comment]
Can you please try now? it should be ok

**Comment by amitabh123** [comment]
Yes it seems to work now. What was the issue?

**Comment by alolis** [comment]
Firewall went loco!

Also, we have a separate project for the websockets api which you can find [here](https://github.com/biteasy/websockets-api/issues)
