### ISSUE TITLE
Biteasy support emails bounce

### ISSUE THREAD

**Issue by schildbach** [biteasy/blockchain-api#34]
I'm filing this here because I don't know a better say to reach you.

Mails to feeback@biteasy.com and support@biteasy.com bounce with this message:

feedback@biteasy.com: host
    3beb58e0adbc4dab843e55ce616b80.pamx1.hotmail.com[65.54.188.78] said: 550
    Requested action not taken: mailbox unavailable (in reply to RCPT TO
    command)

**Comment by alolis** [comment]
Solved
