### ISSUE TITLE
Weak HTTPS Encryption by using SHA-1 signatures

### ISSUE THREAD

**Issue by wischi-chr** [biteasy/blockchain-api#35]
**_This is not an api bug!,**_
_but the support page (https://www.biteasy.com/support) "strongly suggests" to use github because it is the fastest way._

**Details:**
https://www.biteasy.com/ uses SHA-1 signatures (for https) which can be considered broken since 2005 (https://en.wikipedia.org/wiki/SHA-1#Attacks)

![dsasafasf](https://cloud.githubusercontent.com/assets/2495113/9536510/061b6aae-4d2d-11e5-9aed-7915714aaca1.png)

**Comment by alolis** [comment]
We will update the SSL certificate in the next couple of days.

**Comment by alolis** [comment]
SSL certificate has been updated
