### ISSUE TITLE
Problem to show transaction with one multisig out

### ISSUE THREAD

**Issue by romanman** [biteasy/blockchain-api#5]
There is  a problem to show that 
transaction.

https://www.biteasy.com/blockchain/transactions/09dd94f2c85262173da87a745a459007bb1eed6eeb6bfa238a0cd91a16cf7790

I guess, what is exceptional 
here is the 3rd out tx  is a multisig - 
it's really not a standard one. 

Thanks in advance, 
you have a great product.

Roman.

**Comment by biteasy** [comment]
Sorry for the delay Roman! Thank you for the nice words :) 

We have confirmed the bug and we will fix it asap.

**Comment by romanman** [comment]
Cool, let me know

**Comment by biteasy** [comment]
@romanman, we fixed the bug. The transaction will load normally now but I want to remind you that multisig support hasn't been added yet to mainnet, only in testnet. We are going to add it in the next few days and make an announcement about it.

**Comment by romanman** [comment]
Got you. Thanks a lot.
