### ISSUE TITLE
Testnet shows "Main chain"

### ISSUE THREAD

**Issue by dcousens** [biteasy/blockchain-api#8]
Reference: https://www.biteasy.com/testnet/transactions/fc129058bebcd4ba2423cc96dd4fa13b65f471e8bd4f78c98023197e52ecc262

The `In Block` field shows "Main Chain", rather than test net. 

Is this deliberate?

**Comment by biteasy** [comment]
Hello,

That is correct actually. Testnet has a "main" chain as well.

We will re-name the menu "Main Chain" to "Mainnet" in order to make it more clear in case it's confusing.

**Comment by dcousens** [comment]
I assumed that may be the case, but the fact the only way you disambiguate between the networks at the moment is `Blockexplorer -> Main Chain` and  `Blockexplorer -> Testnet`, means you are using the word `Main Chain` to represent two different things:
- The main chain of any particular network, and
- the primary Bitcoin network itself.

A re-name would clarify this. Thanks.

**Comment by biteasy** [comment]
I agree with you and the menu item will be updated soon.

Other than this, how is your general experience with the site so far? Satisfying? Are you using the API as well?

**Comment by dcousens** [comment]
Sent some feedback to the respective email (`feedback@biteasy.com`).
Thanks for the quick response :)

**Comment by biteasy** [comment]
Cheers, we will check it out :)

**Comment by biteasy** [comment]
`Implemented`

**Comment by dcousens** [comment]
Still shows `Main Chain` for me.

**Comment by biteasy** [comment]
You probably need to clear your browser cache!

**Comment by dcousens** [comment]
@biteasy could it be a Cloudflare issue?
Definitely not a local cache problem.

**Comment by biteasy** [comment]
For which page do you still see it as "Main Chain" ?

**Comment by dcousens** [comment]
All of them.

The URL's I've used that show `Main Chain`:
- https://www.biteasy.com/testnet/transactions/fc129058bebcd4ba2423cc96dd4fa13b65f471e8bd4f78c98023197e52ecc262
- https://www.biteasy.com/testnet/blocks/00000000a738c66cd5543f7b8feb6eae5e8fa36116da827727001ecbb660ca2d

**Comment by biteasy** [comment]
Probably some cloudflare caching mambo jambo then because it looks ok on my side.
It will probably auto-resolve soon.
