### ISSUE TITLE
How to bypass CORS

### ISSUE THREAD

**Issue by cimm** [biteasy/blockchain-api#9]
How do I get around the CORS restriction on the Biteasy API?

The [documentation](https://support.biteasy.com/kb/rest-api/request-and-response) mentions:

```
The REST API currently only supports JSON for the request and response formats. That means, that requests should always send the following header:
Content-Type: application/json
```

But to my knowledge a `GET` request doesn't even have a content type.

I could use JSONP and provide a callback function like [https://api.biteasy.com/blockchain/v1/addresses/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp/unspent-outputs?per_page=2&callback=callback-function](https://api.biteasy.com/blockchain/v1/addresses/1dice8EMZmqKvrGE4Qc9bUFf9PX3xaYDp/unspent-outputs?per_page=2&callback=callback)` but Biteasy doesn't seem to understand it needs to wrap the response in the callback function.

**Comment by biteasy** [comment]
There is no CORS restriction at the moment (although this might change in the future) so you do not need to do anything "special" on your part.

**Comment by cimm** [comment]
I was using the testnet and used `test` instead of `testnet` in the URL which caused a CORS warning. I was expecting a 404. Thank you.
